apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}