imagePullSecret: ecr-pull-secret
dbSecretName: db-credentials

backend:
  replicaCount: 3
  image:
    repository: 024848484634.dkr.ecr.eu-west-1.amazonaws.com/david-musumba/backend
    tag: latest
  port: 8000
  probePath: /health
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 3
  image:
    repository: 024848484634.dkr.ecr.eu-west-1.amazonaws.com/david-musumba/frontend
    tag: latest
  port: 8080
  probePath: /
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

ingress:
  className: nginx